### ISSUE TITLE
Comment for outdated AddOn Skins

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8#105]
Hallo,
Every time I will login I got message that version of AddOn Skins are outdated.

I use last version from Curse (8.86).

BR Ralf aka Rolfman

**Comment by Potsrabe** [comment]
O.K. , No Problem!

BR Ralf

**Comment by Potsrabe** [comment]
Hello Rav99,

The error for outdated addon Skins now not more shown, but Square Minimap Buttons from Project Alizroka not more moveable.

BR Ralf

**Comment by Rav99** [comment]
I know, see my second PR :) Sry @Potsrabe , i forget one line but so i have updated raiddebuffs too *g

**Comment by Potsrabe** [comment]
Hello Rav99,
Can You take a look into Your Pull Request for Raid Debuff?

Because I think this will be wrong : "= =" that must be only "=" .

BR Ralf

**Comment by liquidbase** [comment]
Issue is now fixed.

**Comment by Potsrabe** [comment]
Hello,
Now it works fine!

Thank You and BR 

Ralf
