### ISSUE TITLE
Error in Bags since Patch 8.1.5

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8#111]
Hallo since Patch today I get this error massage in Bags:
24x DuffedUI\modules\loot\bags.lua:296: attempt to call method 'SetCheckedTexture' (a nil value)
DuffedUI\modules\loot\bags.lua:296: in function `CreateContainer'
DuffedUI\modules\loot\bags.lua:758: in function `Enable'
DuffedUI\modules\loot\bags.lua:793: in function <DuffedUI\modules\loot\bags.lua:792>

After That only Bags in blizzard design and not in one bag design will be open.

BR Ralf

**Comment by Rav99** [comment]
See pr :)

**Comment by Steviiie** [comment]
Awesome job Rav!

**Comment by Rav99** [comment]
Thx, yw :)

**Comment by Potsrabe** [comment]
Hello, I have test it. It will be working fine !

Thank You !
