### ISSUE TITLE
Problems with new Daily Quest

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8#113]
Hello,
In the new daily quest for Tortullaner "Cycle of Life" I missing the keys to Control the crab.

Key 1 - Left
Key 2 - Right
Key 4 - Grab Tortulla

BR Ralf

**Comment by Rav99** [comment]
Try the pr, maybe it works :) @Potsrabe

**Comment by Potsrabe** [comment]
Hello Rav,

It works fine !

BR ralf
