### ISSUE TITLE
Constant Error

### ISSUE THREAD

**Issue by Valionaa** [liquidbase/DuffedUIv8#116]
Every time I log in I am presented With this error code
Message: ...e\AddOns\DuffedUI\modules\plugins\spellcooldowns.lua:945: bad argument #1 to '?' (table expected, got nil)
Time: Sun Mar 17 18:55:03 2019
Count: 1
Stack: ...e\AddOns\DuffedUI\modules\plugins\spellcooldowns.lua:945: bad argument #1 to '?' (table expected, got nil)
[C]: in function `?'
...e\AddOns\DuffedUI\modules\plugins\spellcooldowns.lua:945: in main chunk

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
  just Looking to see if theres a way around it or a way to fix is

**Comment by liquidbase** [comment]
Which race? Maybe one of the two new allied races?

**Comment by liquidbase** [comment]
I think the problem comes from the previously missing Allied Races Kul Tiran and Zandalar Trolls. With the last commit I added their Racial. Please test that by downloading the version here from Github.
