### ISSUE TITLE
Wrong Color in some Quest Windows

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8#119]
Hello,
In some of the Quest Windows I have wrong Colors. Here are Black Font on Black Backround.

But That will be only for the Questline itself not for the Quest descriptions. Quest Descriptions are White Font on Black Backround.

BR Ralf

**Comment by Rav99** [comment]
Hiho. I have updated AS to the latest change (pull request), maybe it fixed this issue.

**Comment by Potsrabe** [comment]
Hello,
all o.k. now.
