### ISSUE TITLE
Thank You Rav and Merith!

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8#124]
Hello,
Thank You for the Changes for Patch 8.2. ! 
If You need any help for Bug reporting and testing, tell it me.

BR Ralf

(P.S.: I have made this as an Issues , because I have not find a way to send You anythink otherwise. So You can close it after read).

**Comment by Rav99** [comment]
i have made a new pr to see NazjatarFollowerXP on nameplates and bfamission dt.
you can send me errors via bnet if you like?! @Potsrabe

**Comment by Potsrabe** [comment]
Hello,
No Problem use Rolfman#2691
Have You Change something in the Loot Tip? Because if I move mouse over an enemy it Shows me the target of the enemy twince. But this will be only on enemies.

BR Ralf

**Comment by Rav99** [comment]
Nothing changed, i think its a bug in tooltip i take a look 8)
