### ISSUE TITLE
No issue, more a question

### ISSUE THREAD

**Issue by Stroider** [liquidbase/DuffedUIv8#149]
Hey Luiqid and thanks for a fantastic UI also big thanks for the updates from Rav. (You maybe should mention his fork on the master when his fork often are ahead of the master one.)

Will you or Rav make a Classic version since the release of Classic is around the corner? 

Will not play Classic without Duffed, or wow whatsoever. ;)

/Jonas

**Comment by Rav99** [comment]
Aloha Stroider.
My repo is only for testing, here is the right place for DuffedUI :)

**Comment by Stroider** [comment]
That may be so, still it is often or Always more recently updated which can be very useful. 

Doesnt matter tho, you guys are the best, Duffed really is the best ui out there, and I played since vanilla beta so I have some experience when it comes to World of warcraft and addons.

Cheers,

Jonas

**Comment by Stroider** [comment]
Bump :)

**Comment by liquidbase** [comment]
There will not be a version for WoW Classic. You would have to rewrite the entire interface accordingly to have a working version.
The effort is simply too high and there is simply no time to do it.

**Comment by Stroider** [comment]
Ok, thanks for the answer, abit dissapointed of course, but totally understand why and all kudos to you guys keeping Duffed alive for live version.

Thanks again for a superb ui.

/Jonas
