### ISSUE TITLE
Lokal (error)

### ISSUE THREAD

**Issue by Luminoron** [liquidbase/DuffedUIv8#157]
Thanks Rav99 that you keep the project alive.

I have a massiv Error:

```
310x integer overflow attempting to store -nan(ind)
[C]: in function `SetFormattedText'
...ns\DuffedUI\modules\unitframes\elements\elements.lua:65: in function <...ns\DuffedUI\modules\unitframes\elements\elements.lua:55>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "%d%%"
(*temporary) = Infinite
```

**Comment by Rav99** [comment]
Hiho.
I need more information, i cant reproduced this error.
What class are you playing and what action toggle this error? :)

**Comment by Luminoron** [comment]
At this moment Nightelf Demonhunter. (But i become it with all Class)
The error appears when I join raid. But I will test it right now and then give you an accurate feedback.

Other Error: 
If I make a right click on a name this error comes.
(The error is stacked as long as I leave the menu open.)
```
376x FrameXML\UnitPopup.lua:1479: Usage: CheckInteractDistance("unit", distIndex)
[C]: in function `CheckInteractDistance'
FrameXML\UnitPopup.lua:1479: in function <FrameXML\UnitPopup.lua:1474>
FrameXML\UnitPopup.lua:1529: in function `UnitPopup_OnUpdate'
[string "*:OnUpdate"]:3: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = nil
(*temporary) = 0
```

**Comment by Luminoron** [comment]
Update: 
```
382x integer overflow attempting to store -nan(ind)
[C]: in function `SetFormattedText'
...ns\DuffedUI\modules\unitframes\elements\elements.lua:65: in function <...ns\DuffedUI\modules\unitframes\elements\elements.lua:55>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "%d%%"
(*temporary) = Infinite
```

This error always comes when I come through portals in a new zone. 
Only if u change the Zone by loading Screen.

**Comment by Rav99** [comment]
Maybe i fix it, try the latest changes :)

**Comment by Luminoron** [comment]
I will test it and let you know. If I find more things I will report this here. Thank you for your work.

**Comment by Rav99** [comment]
I think its fixed :)
