### ISSUE TITLE
Targetunit_dimmed

### ISSUE THREAD

**Issue by ErwinVersluis** [liquidbase/DuffedUIv8#169]
Even in melee range (was playing on dk when i updated to the latest version published here) the target unit is 80% of the fight dimmed in colour and somtetimes for short moment normal coloured. Reverted addon back to downloaded version of 15 Nov 2019 and colouring is behaving as it should be.

is targeted colouring attempt to make visible if it is in range ?

**Comment by Rav99** [comment]
Out of range the target should be faded. you can toggle this out under unitframes->rangefading

**Comment by ErwinVersluis** [comment]
But the whole time i was in range , melee fighting him and target unit was most of the time faded. Will look at the uniframe options.

**Comment by Rav99** [comment]
I have tested with my dk and dont have this issue, maybe another addon conflicted? Have you tested with only DuffedUI and DuffedUI_Config enabled? Any lua error pops up?

**Comment by Rav99** [comment]
Fixed!
