### ISSUE TITLE
[ADDON_ACTION_BLOCKED] AddOn 'DuffedUI' tried to call the protected function 

### ISSUE THREAD

**Issue by ErwinVersluis** [liquidbase/DuffedUIv8#173]
(duffedui 8.95)
when you are solo and interrupt something then the error appear and no shout text. (that moment you should shout that you interrrupted). In a group you get no error and the message is showing normally.

273x [ADDON_ACTION_BLOCKED] AddOn 'DuffedUI' tried to call the protected function 'UNKNOWN()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: ?
[C]: in function `CreateFrame'
FrameXML\SecureGroupHeaders.lua:164: in function <FrameXML\SecureGroupHeaders.lua:123>
FrameXML\SecureGroupHeaders.lua:488: in function <FrameXML\SecureGroupHeaders.lua:387>
[C]: in function `Show'
FrameXML\SecureStateDriver.lua:100: in function <FrameXML\SecureStateDriver.lua:95>
FrameXML\SecureStateDriver.lua:127: in function <FrameXML\SecureStateDriver.lua:119>

**Comment by liquidbase** [comment]
Issue fixed with version 8.97
