### ISSUE TITLE
interrupt text, minimap buttons, and bank bags

### ISSUE THREAD

**Issue by ErwinVersluis** [liquidbase/DuffedUIv8#189]
Group, Raid or Solo if you interrupt something nothing is mentioned anymore. doesnt matter the setting of "enable interrupt announcement" if its enabled or disabled. ( duffed --> enable interrupt announcement ). If possible to fix could the text be changed back to what you interrupt, instead of the ability you use to interrupt like it was some time ago. When the interrupt messages were still said, it was telling like you kick someting instead of you stopped the healing cast.

Minimaps buttons only show when the option is disabled ( general -> enable minimap button )

When you open the reagent "bank" the items you move from your bag are still placed in the normal bank slot instead of the reagant one. ( is already sometime this way, not due to latest update).

**Comment by Rav99** [comment]
> Minimaps buttons only show when the option is disabled ( general -> enable minimap button )

If you have Minimap Buttons enabled in DuffedUI you have a little icon on the bottom left corner of the minimap, click it and the buttons fades in.

> Reagent bank issue

Works fine for me. I open the bank, click the reagent bank icon and then i pull the reagent to the free bags icon and it goes to reagent bank, not normal bank. the arrow to pull all reagents works fine too for me.

> Interrupt issue

Will check this one

**Comment by ErwinVersluis** [comment]
the green mini dot appearing when it is enabled i had not noticed it. thx.

for the reagent bank. Yes when i move an item "manual" from bag to reagent bank it works. but when i right click an item in mine bag it is moved towards mine normal bank instead of the opened reagent one.

**Comment by ErwinVersluis** [comment]
Also for sometime the middle-mouse click on the minimap didnt work anymore. recently in one of the last updates it was working again so thought it was fixed. In the last update it isnt working againt.

**Comment by ErwinVersluis** [comment]
scratch that is working sort of. it is just most of the time not reacting on middle mouse, and rarely it does. After it finally picks up the middle-mouse it reacts better next time. Buf it you leave it alone and try later the rare reaction is there again.

**Comment by liquidbase** [comment]
The mouse wheel click depends on how you have configured your device and which system you are using. On Linux / Windows this works with a normal mouse as you would expect. MacOS likes to cause problems. But that is more due to Apple, because they have a strange understanding of globally standardized processes.
Because of the reagent bank you have the function "store all reagents" that you can use. This means that all reagents are sorted accordingly and that stacks are also filled up.
A fix is currently being worked on for the interrupt announcement and should be available soon.

**Comment by liquidbase** [comment]
Issues fixed with v8.97
