### ISSUE TITLE
Raid Frame - Only dps layout

### ISSUE THREAD

**Issue by ErwinVersluis** [liquidbase/DuffedUIv8#195]
In the download version of 26 Jul and 20 Jul mine default raid frame setting of healer is swapped  to dps layout even if the layout is set to healer. Change the option dps and back to healer have no effect.

Only when i revert back to the version of 17 Jul i have mine healer layout back. Every character of mine is using that same layout. In the latest version how can i have the correct view ? Is there a need to remove the wtf files before using latest version ?

**Comment by liquidbase** [comment]
Thanks for your feedback. I will check this today.

**Comment by liquidbase** [comment]
How do you change the layout? Do you do that via the config or via the menu on the spec switcher? In our own tests, switching between Heal and DPS works smoothly.

**Comment by ErwinVersluis** [comment]
through the setting of duffedui. You can select the layout. Eventho it was set to healer it was shown the dps layout after upgrading the newer version. Did replace the version while game was not running. When i tried to swap layout within the game from healer to dps and then later healer nothing happend. Like i said i use the "healer" layout with all classes (dps and healer). With the last version i was on mine deathknight , the addon up previous of that i was on mine mage. The healer layout is more organized then the dps which just stacks dps on top of each other.

When i revert to mine original version i head mine layout back. Only thing i havent checked if i need to wipe the wtf of all the addons used by duffed after upgrading to the latest version.

**Comment by ErwinVersluis** [comment]
Can make an attempt and see if cleared the config files makes any difference. Will save the wtf version before removing them and upgrade to last version and see if correct layour is down. Will attempt that this evening.

**Comment by ErwinVersluis** [comment]
wiping all settings has no effect. eventho it is set at healer layout the dps one is showing ( at deathknight char : horde)

**Comment by ErwinVersluis** [comment]
swapped to mine healer shaman , but also the wrong layout is showing. revert back now to the old duffed version and layout is correct again.  swapping in old version between dps and healer layour works there.

**Comment by liquidbase** [comment]
Please provide a screenshot from your ConfigUI with selected Raid Frame Options. I am currently assuming that there is a problem with the keyword. I would also like to ask you to download the current version from GitHub. Before you copy the version into the interfaces folder, please delete the folders DuffedUI and DuffedUI_Config from the interfaces folder.

The keywords for the ConfigUI is "heal" for the healer layout and "damage" for the DPS layout.

**Comment by liquidbase** [comment]
Version 8.99 is now online. This fixes the issue with the ConfigUI and the SpecSwitcher.

**Comment by ErwinVersluis** [comment]
![WoWScrnShot_073120_212151](https://user-images.githubusercontent.com/20583191/89074261-627d3680-d37c-11ea-8d7c-b3da957ea1b7.jpg)
![duffeduiconfig](https://user-images.githubusercontent.com/20583191/89074287-6c9f3500-d37c-11ea-9edd-a2699d3f7a20.jpg)

**Comment by ErwinVersluis** [comment]
ok. will update uploaded version.
