### ISSUE TITLE
Removed Options in latest commit

### ISSUE THREAD

**Issue by Dahgoth** [liquidbase/DuffedUIv8#25]
1. Centered Raid Frames in Heal Layout (and all layout settings like health percents outside of player and target frames etc.).
2. Horizontal orientation on Side (Action) Bars.

Will it be returned?

**Comment by Tarilya** [comment]
1. n/A

2. I hope this will help oyu

1. Open DuffedUI/config/config.lua
Search

["Leftsidebars"] = false,
["Rightsidebars"] = false,


Replace it with

["Leftsidebars"] = false,
["Leftsidebarshorizontal"] = false, 
["Rightsidebars"] = false, 
["Rightsidebarshorizontal"] = false, 


2. Open DuffedUI/modules/actionbars/bar3.lua
Search
b:SetSize(D["SidebarButtonsize"], D["SidebarButtonsize"])

Replace it with

if C["actionbar"]["Leftsidebarshorizontal"] then b:SetSize(D["buttonsize"], D["buttonsize"]) else b:SetSize(D["SidebarButtonsize"], D["SidebarButtonsize"]) end


Search

if i == 1 then
 b:SetPoint("TOPLEFT", bar, D["buttonspacing"], -D["buttonspacing"])
 elseif i == 7 then
 b:SetPoint("TOPRIGHT", bar, -D["buttonspacing"], -D["buttonspacing"])
 else
 b:SetPoint("TOP", b2, "BOTTOM", 0, -D["buttonspacing"])
 end


Replace

if C["actionbar"]["Leftsidebarshorizontal"] then
 if i == 1 then b:SetPoint("BOTTOMLEFT", bar, D["buttonspacing"], D["buttonspacing"]) else b:SetPoint("LEFT", b2, "RIGHT", D["buttonspacing"], 0) end
 else
 if i == 1 then
 b:SetPoint("TOPLEFT", bar, D["buttonspacing"], -D["buttonspacing"])
 elseif i == 7 then
 b:SetPoint("TOPRIGHT", bar, -D["buttonspacing"], -D["buttonspacing"])
 else
 b:SetPoint("TOP", b2, "BOTTOM", 0, -D["buttonspacing"])
 end


3. Open DuffedUI_ConfigUI/local/german.lua
Search

 DuffedUIConfigUILocalization.actionbarSidebarButtonsize = "Set size of buttons for sidebars on chat (only when vertical)"

Add after this line
DuffedUIConfigUILocalization.actionbarLeftsidebarshorizontal = "Set left SideBar horizontal"
DuffedUIConfigUILocalization.actionbarRightsidebarshorizontal = "Set right SideBar horizontal"
