### ISSUE TITLE
Error in World of Warcraft UI

### ISSUE THREAD

**Issue by Doc2812** [liquidbase/DuffedUIv8#27]
Here are the errors that I am getting:

Date: 2016-06-06 20:05:36
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\DuffedUI\modules\misc\raidutilities.lua line 90:
   attempt to index global 'CompactRaidFrameManagerDisplayFrameLeaderOptionsRaidWorldMarkerButton' (a nil value)
Debug:
   ...rface\AddOns\DuffedUI\modules\misc\raidutilities.lua:90: in main chunk
Locals:
D = <table> {
 countOffsets = <table> {
 }
 SetFontString = <function> defined @Interface\AddOns\DuffedUI\core\func_Core.lua:64
 MyName = "Timeron"
 PostUpdateAura = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:298
 petbuttonsize = 29
 DataTextPosition = <function> defined @Interface\AddOns\DuffedUI\core\func_Core.lua:74
 UpdateTargetDebuffsHeader = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:327
 MyRealm = "Skywall"
 move = <unnamed> {
 }
 IconCoord = <table> {
 }
 ScreenWidth = 1920
 MicroMenu = <table> {
 }
 SidebarButtonsize = 23
 ShiftBarUpdate = <function> defined @Interface\AddOns\DuffedUI\core\func_Core.lua:160
 PetBarUpdate = <function> defined @Interface\AddOns\DuffedUI\core\func_Core.lua:192
 CreateBtn = <function> defined @Interface\AddOns\DuffedUI\core\func_Core.lua:337
 UpdateManaLevel = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:434
 Class = "WARRIOR"
 ScreenHeight = 1080
 UnitColor = <table> {
 }
 Dummy = <function> defined @Interface\AddOns\DuffedUI\core\constants.lua:3
 ColorTemplate = <table> {
 }
 ChatSetup = <function> defined @Interface\AddOns\DuffedUI\core\install.lua:3
 Credits = <table> {
 }
 CustomCastDelayText = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:379
 SpawnMenu = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:37
 buffids = <table> {
 }
 PostUpdateHealth = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:65
 Font = <function> defined @Interface\AddOns\DuffedUI\core\func_Font.lua:41
 Version = "8.34"
 DataTextTooltipAnchor = <function> defined @Interface\AddOns\DuffedUI\core\func_Core.lua:131
 EclipseDirection = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:417
 ShowPopup = <function> defined @Interface\AddOns\DuffedUI\core\popup.lua:65
 HyperlinkMouseover = <function> defined @Interface\AddOns\DuffedUI\core\func_Core.lua:31
 Guild = "The Dark Syndicate"
 buttonspacing = 4
 CustomCastTime = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:377
 noscalemult = 0.71111111111111
 Client = "enUS"
 UpdateThreat = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:455
 HidePortrait = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:341
 PanelColor = ""
 Spells = <table> {
 }
 PostUpdateHealthRaid = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:122
 SkinFuncs = <table> {
 }
 MyRace = "Draenei"
 HasteTicks = <table> {
 }
 raidscale = 1
 ChannelTicks = <table> {
 }
 VersionNumber = 8.34
 CreatePopup = <table> {
 }
 Delay = <function> defined @Interface\AddOns\DuffedUI\core\func_Core.lua:311
 Patch = "6.2.4"
 PostCreateAura = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:249
 SetGridGroupRole = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:470
 BuildText = "21742"
 MLAnchorUpdate = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:429
 CastBar = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:381
 SetPerCharVariable = <function> defined @Interface\AddOns\DuffedUI\core\init.lua:18
 Resolution = "1920x1080"
 PortraitUpdate = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:348
 mult = 1
 CommaValue = <function> defined @Interface\AddOns\DuffedUI\core\func_Core.lua:54
 Scale = <function> defined @Interface\AddOns\DuffedUI\core\video.lua:33
 PostUpdatePetColor = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:148
 Level = 100
 createAuraWatch = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:500
 build = 21742
 updateAllElements = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:8
 RGBToHex = <function> defined @Interface\AddOns\DuffedUI\core\func_Core.lua:243
 debuffids = <table> {
 }
 ReleaseDate = "May 17 2016"
 InfoLeftRightWidth = 370
 petbuttonspacing = 4
 Toc = 60200
 ReverseTimer = <table> {
 }
 PostUpdatePower = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:164
 FormatTime = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:199
 ShortValue = <function> defined
AddOns:
  Swatter, v5.21f.5579 (SanctimoniousSwamprat)
  Accountant, v6.02.60200
  AddOnSkins, v3.30
  DuffedUI, v8.34
  DuffedUIConfigUI, v8.34
  BlizRuntimeLib_enUS v6.2.4.60200 <none>
  (ck=b3)

--------------------------------------------------------------------------------------------------------------------------------
Date: 2016-06-06 20:05:36
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\DuffedUI\modules\misc\kill.lua line 15:
   attempt to index global 'CompactRaidFrameManager' (a nil value)
Debug:
   DuffedUI\modules\misc\kill.lua:15:
      DuffedUI\modules\misc\kill.lua:5
Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "ADDON_LOADED"
addon = "DuffedUI"
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'CompactRaidFrameManager' (a nil value)"
C = <table> {
 nameplate = <table> {
 }
 misc = <table> {
 }
 general = <table> {
 }
 media = <table> {
 }
 bags = <table> {
 }
 datatext = <table> {
 }
 chat = <table> {
 }
 loot = <table> {
 }
 raid = <table> {
 }
 castbar = <table> {
 }
 tooltip = <table> {
 }
 classtimer = <table> {
 }
 font = <table> {
 }
 merchant = <table> {
 }
 actionbar = <table> {
 }
 duffed = <table> {
 }
 unitframes = <table> {
 }
 cooldown = <table> {
 }
 auras = <table> {
 }
}

AddOns:
  Swatter, v5.21f.5579 (SanctimoniousSwamprat)
  Accountant, v6.02.60200
  AddOnSkins, v3.30
  DuffedUI, v8.34
  DuffedUIConfigUI, v8.34
  BlizRuntimeLib_enUS v6.2.4.60200 <none>
  (ck=b3)

---------------------------------------------------------------------------------------------------------------------------
Date: 2016-06-06 20:05:37
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-LDB\DBM-LDB.lua line 6:
   Wrong object type for function
Debug:
   [C]: CreateFrame()
   DBM-LDB\DBM-LDB.lua:6: in main chunk
Locals:
(*temporary) = "Frame"
(*temporary) = "DBMLDBDropdownFrame"
(*temporary) = frame {
 0 = <userdata>
}
(*temporary) = "UIDropDownMenuTemplate"

AddOns:
  Swatter, v5.21f.5579 (SanctimoniousSwamprat)
  Accountant, v6.02.60200
  AddOnSkins, v3.30
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v5.21f.5579 (SanctimoniousSwamprat)
  Configator, v5.1.DEV.396(/embedded)
  DBMCore, v
  DBMDefaultSkin, v
  DBMLDB, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DuffedUI, v8.34
  DuffedUIConfigUI, v8.34
  LibExtraTip, v5.12.DEV.395(/embedded)
  SlideBar, v5.21f.5579 (SanctimoniousSwamprat)
  Stubby, v5.21f.5579 (SanctimoniousSwamprat)
  TipHelper, v5.12.DEV.389(/embedded)
  BlizRuntimeLib_enUS v6.2.4.60200 <none>
  (ck=247)

**Comment by liquidbase** [comment]
Under what circumstances you get this error?

**Comment by Doc2812** [comment]
Sir,

 

                After I select the toon I want to play and get loaded into the game.

**Comment by Rav99** [comment]
Have you tryed with only DuffedUI and DuffedUI_Config only activated?

**Comment by liquidbase** [comment]
I know the issue.
Please delete all files are called AddOns.txt and located within the folder WTF. Normally one finds the files amongst:
`\World of Warcraft\WTF\Account\<ACCNAME>\<Server>\<Character>`
After that the first issue should be gone.

The third issue come from DBM itself, please update DBM. It's not a DuffedUI related issue.

greetz
liquid
