### ISSUE TITLE
Low mana error

### ISSUE THREAD

**Issue by Rav99** [liquidbase/DuffedUIv8#37]
On warlock  lvl 17, oom in combat. v8.47

`Message: Interface\AddOns\DuffedUI\core\func_UF.lua:27: attempt to index field 'fadeout' (a nil value)
Time: 08/26/16 20:11:53
Count: 1
Stack: Interface\AddOns\DuffedUI\core\func_UF.lua:27: in function <Interface\AddOns\DuffedUI\core\func_UF.lua:23>
Interface\AddOns\DuffedUI\core\func_UF.lua:486: in function <Interface\AddOns\DuffedUI\core\func_UF.lua:472>

Locals: self = DuffedUIFlashInfo {
parent = oUF_Player {
}
ManaLevel = <unnamed> {
}
anim = Flash {
}
0 = <userdata>
}
duration = 0.3
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0.3
(*temporary) = "attempt to index field 'fadeout' (a nil value)"
SetUpAnimGroup = <function> defined @Interface\AddOns\DuffedUI\core\func_UF.lua:`

**Comment by liquidbase** [comment]
Fixed with the last commit.
