### ISSUE TITLE
AFK Screen

### ISSUE THREAD

**Issue by jubilus** [liquidbase/DuffedUIv8#42]
Hello,

I had to go afk for a bit today and when I came back the camera was slowly spinning around my character with "DuffedUI 8.49" at the bottom. I can't seem to find a way to turn this screen off.

**Comment by liquidbase** [comment]
Simply move your character to stop the AFK-Camera. The plugin is adjusted to stop the the afk screen on moving, combat start or death of your character.

**Comment by dwfmagik** [comment]
Sometimes it does bug, type /reload ((even thought you can't see the chat, just type it and press enter.)). It will fix it for those rare bugs.

**Comment by jubilus** [comment]
Moving the character didn't stop the afk camera from running. Typing /afk and then /afk again worked. I guess somehow it didn't get the signal that I was no longer afk when I moved. I guess /reload would have also worked.

**Comment by liquidbase** [comment]
Alright I check the issue and try first to reproduce it. Maybe I have
missed something.

**Comment by liquidbase** [comment]
Please check if the option auto turn off afk enabled is. If not please check it. This can be the only issue for not disable the afk-screen in a automatic way.
