### ISSUE TITLE
Addonskins

### ISSUE THREAD

**Issue by xSaoCx** [liquidbase/DuffedUIv8#50]
I know that you aren't accepting requests/etc. But, since 7.1, my addonskins has been slightly broken. lua errors/etc. I'm not asking for a new feature, just hoping you can take a look at the skins to fix it

Thank you in advance!

**Comment by Dotmeharder** [comment]
I am having the same issues with the LUA Error as well, 

Message: ...nterface\AddOns\DuffedUI\modules\tooltip\tooltip.lua:169: attempt to call method 'GetAttribute' (a nil value)
Time: 10/30/16 19:32:07
Count: 5
Stack: ...nterface\AddOns\DuffedUI\modules\tooltip\tooltip.lua:169: in function `SetColor'
...nterface\AddOns\DuffedUI\modules\tooltip\tooltip.lua:232: in function <...nterface\AddOns\DuffedUI\modules\tooltip\tooltip.lua:227>
[C]: in function `Show'
Interface\AddOns\DuffedUI\modules\tooltip\itemid.lua:39: in function <Interface\AddOns\DuffedUI\modules\tooltip\itemid.lua:26>
Interface\AddOns\DuffedUI\modules\tooltip\itemid.lua:113: in function <Interface\AddOns\DuffedUI\modules\tooltip\itemid.lua:99>
[C]: ?
[C]: ?
[C]: in function `SetHyperlink'
Interface\AddOns\DuffedUI\core\func_Core.lua:19: in function <Interface\AddOns\DuffedUI\core\func_Core.lua:15>

Locals: self = GameTooltip {
 0 = <userdata>
 SetCurrencyByID = <function> defined =[C]:-1
 numMoneyFrames = 1
 insettop = <unnamed> {
 }
 comparing = false
 shoppingTooltips = <table> {
 }
 SetCurrencyTokenByID = <function> defined =[C]:-1
 insetbottom = <unnamed> {
 }
 hasMoney = 1
 insetinsidebottom = <unnamed> {
 }
 isInsetDone = true
 SetHyperlink = <function> defined =[C]:-1
 updateTooltip = 0.037999995797873
 SetUnitBuff = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined @Interface\AddOns\DuffedUI\modules\plugins\currency.lua:219
 insetinsideleft = <unnamed> {
 }
 insetinsideright = <unnamed> {
 }
 SetUnitAura = <function> defined =[C]:-1
 IsSkinned = true
 needsReset = true
 insetright = <unnamed> {
 }
 SetUnitDebuff = <function> defined =[C]:-1
 insetinsidetop = <unnamed> {
 }
 insetleft = <unnamed> {
 }
}
GetMouseFocus = <unnamed> {
 0 = <userdata>
 messageInfo = <table> {
 }
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 messageInfo = <table> {
 }
}
(*temporary) = "unit"
(*temporary) = "attempt to call method 'GetAttribute' (a nil value)"
unpack = <function> defined =[C]:-1
C = <table> {
 nameplate = <table> {
 }
 misc = <table> {
 }
 general = <table> {
 }
 media = <table> {
 }
 duffed = <table> {
 }
 datatext = <table> {
 }
 chat = <table> {
 }
 loot = <table> {
 }
 raid = <table> {
 }
 castbar = <table> {
 }
 tooltip = <table> {
 }
 classtimer = <table> {
 }
 merchant = <table> {
 }
 actionbar = <table> {
 }
 bags = <table> {
 }
 unitframes = <table> {
 }
 cooldown = <table> {
 }
 auras = <table> {
 }
}
Colors = <table> {
 runes = <table> {
 }
 tapped = <table> {
 }
 reaction = <table> {
 }
 power = <table> {
 }
 class = <table> {
 }
 disconnected = <table> {
 }
}
HealthBar = GameTooltipStatusBar {
 0 = <userdata>
 Text = <unnamed> {
 }
 backdrop = <unnamed> {
 }
 text = <unnamed> {
 }
}


This is what i get, plz help.

**Comment by Rav99** [comment]
I have try to fix the issues with addonskins and tooltip. pls test the files on my repo, if it works i make a pull request for liquid so he can test himself and merged the change.
https://github.com/Rav99/DuffedUIv8

**Comment by Stroider** [comment]
Working like a charm.

**Comment by xSaoCx** [comment]
Working for me. Thank you =D
