### ISSUE TITLE
Reagant Bank?

### ISSUE THREAD

**Issue by Admireeee** [liquidbase/DuffedUIv8#57]
I use to be stubborn about the blizz UI but i love how this looks
but i can't seem to use my reagant bank in it?
This is what i see. I would love to see reagant bank access.
http://i.imgur.com/yc9whm7.jpg

**Comment by liquidbase** [comment]
Make a update with the current code from github. Access to the download link:

Code => Hit Clone or Download => Download ZIP

**Comment by Admireeee** [comment]
Gave it a try and had the same issue as in the screenshot above.

**Comment by liquidbase** [comment]
Please check if you deleted first the folders of the old version from DuffedUI. 
Upgradepath should be: Delete old folders => Copy new folders => Start Client

No one have this issue expect you. And please make sure you download the included AddOnSkins and Enhanced Config only from the package @wowinterface or @github.

**Comment by liquidbase** [comment]
Works as planned and expected - Tested it for the last 7 days
