### ISSUE TITLE
Search ind bag / Bank not work

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8#59]
Hallo,
I have the newest files from Github, but the Search function in Bag abd Bank do not work. Only Bag Symbols im left of normal bag will be gray out, but searched items in bag are not higlighted and not searched Items are not Grey out.

BR Ralf

**Comment by liquidbase** [comment]
See this issue as well. 
I will try to find a solution this week.

**Comment by Rav99** [comment]
Fixed in PR ... AddOnSkins drives me crazy ...

**Comment by Potsrabe** [comment]
Hello Rav,
Nice work, but cant you take a look at reagnt bank? Because Normal bank and Bag are working, but Reagent Bank not.
 
I have take a look into Code, but cannot find an error.

BR Ralf
