### ISSUE TITLE
FPS Performance Problem

### ISSUE THREAD

**Issue by Grobi666** [liquidbase/DuffedUIv8#60]
Hi,

i have a Performance Problem with this lovely UI ;) (current version)
Without the Addon I have >100 FPS, with this Addon i get <60.
Is there a "FPS-Lock" or something?

sorry for my bad English ;)

**Comment by liquidbase** [comment]
Do you have the fps issue only with DuffedUI and his parts in the package
or with all your add-ons?
Drops the fps every time or only in specific situations?

Please describe your issue with all informations you have. Only "I have fps
drops." isn't helpful for the team.

**Comment by Grobi666** [comment]
Hallo,
soweit ich in Erinnerung habe kannst/verstehst du Deutsch ;)

Ich habe das Problem nur wenn ich die Addons "DuffedUI" und "DuffedUI Config UI" geladen habe.
Während ich ohne diese beiden Addons FPS über 100 habe (GTX1070, i7 Prozessor), fallen diese unter 60 FPS beim aktivieren von DuffedUI.
Ich habe gerade zum Test mal TukUI mit dem AlhanaUI Zusatzaddon installiert um zu schauen wie es sich damit verhält. Hier habe ich weiterhin die hohen FPS.
![tukui_aktiv](https://cloud.githubusercontent.com/assets/23306800/20051802/2c402f56-a4d1-11e6-804d-65932ee8b1a6.PNG)
![duffed_inaktiv](https://cloud.githubusercontent.com/assets/23306800/20051803/2c406598-a4d1-11e6-8bb4-85cf6a911e26.PNG)
![duffed_aktiv](https://cloud.githubusercontent.com/assets/23306800/20051801/2c3dbcc6-a4d1-11e6-9cde-d10d8ec56e48.PNG)

**Comment by liquidbase** [comment]
Ja Deutsch verstehe ich in der Tat :)
Dann wäre interessant zu wissen in welchen Situationen die FPS dropt.
Grund für die Frage dabei ist, dass in den Legion-Zone größere und bessere
Texturen genutzt werden. Und ich selbst (wenn ich zum spielen komme) habe
durchschnittlich 170 - 200 FPS.

**Comment by Grobi666** [comment]
Die Screenshots habe ich in der "Schwarzen Festung" (Todesritter Ordenshalle) gemacht.
Das Phänomen habe ich eigentlich immer und überall beim aktivieren des Addons.
Kurzform: Addon an -> halbe FPS :(  auch wenn alle anderen Addons deaktiviert sind (DBM, Recount usw..)
Hab auch schon den WTF und Cache-Ordner von WOW geleert, Grafiktreiber aktuell, usw..

**Comment by Grobi666** [comment]
Hab noch nen kleinen Nachtrag, evtl hilf das weiter.
Hatte die Version 8.49 noch auf der Platte gefunden, hier passt alles. Hohe FPS mit dem UI. (mal abgesehen von den ganzen Fehlermeldungen ;)  )

**Comment by liquidbase** [comment]
Dann muss man da nochmal schauen was sich zwischen 8.53 und 8.55 geändert hat was die Drops verursacht. Gebe ich aber direkt mal weiter, da ich die nächsten zwei Wochen selbst nicht da bin.

**Comment by Tryllemann** [comment]
Try to disable SlotItemLevel

**Comment by liquidbase** [comment]
Will check the possibility for this issue with Itemlevel-Script.

**Comment by Rav99** [comment]
Perhaps a simple update of the libitemupgradeinfo fix ... will test it.

**Comment by liquidbase** [comment]
Download the latest source from GitHub and check if the issue persist.

**Comment by Grobi666** [comment]
Hiho,

hab gerade das aktuelle DuffedUI installiert. Schaut gut aus, FPS konstant und die Suche funktioniert im Rucksack wieder :)
Danke!
