### ISSUE TITLE
Copychat

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8#63]
Hello,
New Copychat make not more Errors, but it don't work. It Opens a new window, bot this have only textures, but will be empty.  In the past I have seen in this Windows the Chat so I can Copy and paste the Chat.

BR Ralf

**Comment by Rav99** [comment]
Pls try latest PR ... think i got it :)

**Comment by Potsrabe** [comment]
Hello Rav,
It works fine!
