### ISSUE TITLE
Error on promoting raidmembers to main tank

### ISSUE THREAD

**Issue by marco-kretz** [liquidbase/DuffedUIv8#68]
Hey guys,

really love ur UI but one thing that really bothers me is, that, when I try to promote a raidmember to maintank, an error occurs saying "DuffedUI is using an old function" and I have to disable DuffedUI, promote ppl, re-enable.

**Comment by liquidbase** [comment]
How do you promote raid members to maintank? Via the button "Tank" at the raidcontrol-dropdown or the raid window from the social window?

And I think the error don't say it is a old function. I think you mean "a function that is reserved for the Blizzard interface". If this error occur make a reload of the UI. Issue of this error message is the broken code for dropdowns from Blizzard. 
If this is not the error please look if you get a Lua-error. If yes, then please post this to me.

As a side note, I use this function as well and have no issues with it. I can promote every raid member to maintank or mainassist I want with the button "Tank" or "Main Assist".

**Comment by marco-kretz** [comment]
Hey, danke für die schnelle Antwort. Screenshot:

![2017-07-10 12_30_52-world of warcraft](https://user-images.githubusercontent.com/2982363/28014093-afd0096c-656b-11e7-8727-d61346554f65.png)
![wowscrnshot_071017_123002](https://user-images.githubusercontent.com/2982363/28014092-afcd968c-656b-11e7-9ed1-6245fc2793fb.jpg)

**Comment by liquidbase** [comment]
Ja das ist die Fehlermeldung wegen dem broken Blizzard-Code für die Dropdowns. Da hast du sehr wahrscheinlich vorher ein Dropdown aufgerufen was das UI dann blockiert. Da reicht dann ein einfacher Reload und das ganze sollte wieder gehen.
Alternativ kannst du auch das das Raidtool nehmen was normal am oberen Bildschirmrand sitzt wenn du Assistant oder Leader bist, darüber geht das auf alle Fälle, ist der Button Tank. So benutze ich das ganze auch.

**Comment by marco-kretz** [comment]
Alles klar, dann werde ich das so machen. Danke!
