### ISSUE TITLE
Error on leaving battleground queue

### ISSUE THREAD

**Issue by piperun** [liquidbase/DuffedUIv8#70]
Not sure on whenever or not this error message is sufficient enough, but when I tried to leave the queue it was blocked and the error message came up.

Date: 2017-11-30 04:20:38
ID: -1
Error occured in: AddOn: DuffedUI
Count: 4
Message: Error: AddOn DuffedUI attempted to call a forbidden function (func()) from a tainted execution path.
Debug:
   [C]: ?
   ..\FrameXML\QueueStatusFrame.lua:725: func()
   ..\FrameXML\UIDropDownMenu.lua:791: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v7.3.1 (<%codename%>)
  AddOnSkins, v3.61
  Babylonian, v5.1.DEV.332(/embedded)
  BigWigs, vv76
  BigWigsCore, v
  BigWigsPlugins, v
  Binder, v2.6.2
  Configator, v5.1.DEV.431(/embedded)
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DuffedUI, v8.71
  DuffedUIConfigUI, v8.71
  Gatherer, v7.3.1
  LittleWigs, vv7.3.1
  SlideBar, v7.3.1 (<%codename%>)
  TradeSkillMaster, vv3.6.37
  TradeSkillMasterAccounting, vv3.0.20
  TradeSkillMasterAppHelper, vv3.0.4
  TradeSkillMasterAuctionDB, vv3.1.18
  TradeSkillMasterAuctioning, vv3.0.16
  TradeSkillMasterCrafting, vv3.2.5
  TradeSkillMasterDestroying, vv3.1.7
  TradeSkillMasterMailing, vv3.0.18
  TradeSkillMasterShopping, vv3.4.7
  TradeSkillMasterVendoring, vv3.0.7
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v7.3.2.70300 <none>
  (ck=435)

**Comment by liquidbase** [comment]
This is the usual taint for dropdowns.
The problem here is that I can not address the appropriate frame to fix the bug. If the bug occurs again (which is not always the case), a reload of the interface would have to fix the bug.
