### ISSUE TITLE
Addon Skin DBM

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8#74]
Hallo,
Ich habe die aktuelle Version von Github installiert und bekomme beim Login in WoW die folgende Warnung:

AddOnSkins 3.69: there was an error in the DBM skin

Wenn ich das im Gitlab von Azilroka richtig gesehen habe, ist der Fehler wohl dort in der aktuellen Version behoben.

Gruß Ralf aka Rolfman

**Comment by liquidbase** [comment]
Muss ich noch anpassen.
Kann ich aber erst machen wenn ich wieder zuhause bin. Sitze aktuell bei einem Kunden. Sollte aber das Wochenende, spätestens Montag drin sein.

**Comment by Rav99** [comment]
@Potsrabe Ich hab einen PR erstellt, einfach das File tauschen und DBM sollte wieder funzen.

**Comment by Potsrabe** [comment]
Hallo Ihr Zwei.
Danke, werde das gleich mal testen.

Gruß Ralf

**Comment by Potsrabe** [comment]
So, habe das getestet. Gute Arbeit, die Warnung ist weg.

Danke ! Gruß Ralf
