### ISSUE TITLE
Alles O.k.

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8#77]
Hallo,
Die Version hier vom Github läuft erst einmal wieder stabil ! Super Arbeit!
Wie ist das mit dem Project Azilroka ? Irgendwie fehlt mir das Eingebettete Details! und das Minimap Button Frame (habe da jetzt erst einmal wieder das Original installiert).

Gruß Ralf

**Comment by liquidbase** [comment]
AddOnSkins und Project Azilroka kommen erst dran wenn das UI soweit fertig ist. Da gibt es noch ein, zwei Sachen die im Code derzeit mit --[[broken]]-- markiert sind. Bevor die nicht gefixt sind fange ich mit den beiden nicht an

**Comment by Potsrabe** [comment]
O.K.
Mal dazu eine Frage. Wie machst Du das eigentlich, testest Du das nach dem Motto Probieren und dann weitergucken? Oder gibt es irgendwie Debugging Tools? Ich habe nämlich mal versucht den Groupcalendar5 anzupassen, aber irgendwie komme ich da nicht weiter. Irgendwie sieht man nicht, wann ruft er eigene Funktionen auf und wann Blizzard. Irgendwie hat er da auch ein Konstrukt (sieht für mich aus. als ob das ein Call auf Blizzard sein soll:
_, self.CurrentMonth, self.CurrentDay, self.CurrentYear = GroupCalendar.WoWCalendar:CalendarGetDate()
Jetzt hat sich die Funktion bei Blizzard aber geändert (statt CalendarGetDate neu C_Calendar.GetDate) wenn ich das aber ändere in:

self.CurrentDate = GroupCalendar.WoWCalendar:C_Calendar.GetDate()
self.CurrentMonth = self.CurrentDate.month
self.CurrentDay = self.CurrentDate.monthDay
self.CurrentYear = self.CurrentDate.year

Bekomme ich einen Lua Fehler wegen dem Punkt vor GetDate. Lasse ich GroupCalendar.WoWCalendar: weg, werden die Variablen richtig gesetzt.

Danke!

Gruß Ralf

**Comment by liquidbase** [comment]
Das meiste kann man per Trial & Error machen wenn es sich nicht gerade um das Release eines neuen AddOns handelt. Ist es ein neues AddOn, so wie jetzt BfA, dann nutze ich zum einen den Quellcode des StandardUI um zu sehen was sich geändert hat und zum anderen den Slashbefehl /eventtrace. Der Rest ist ehrlich gesagt simples Lesen und suchen, sowie Erfahrung.

Auf Github findet man auch eine ganze Menge an Repos die direkt wowui-source heissen, bei den meisten sollte die aktuelle Version des StandardUI drin sein mit allen dazugehörigen Funktionen und Aufrufen. Als AddOn-Entwickler greift man am Ende nämlich eh auf die Blizardfunktionen zu.

**Comment by Potsrabe** [comment]
Hallo,
Ich habe da noch einen merkwürdigen Effekt. Bei den folgenden Klassen Hexenmeister, Paladin und Mönch sind über dem ouF so merkwürdige farbige Punkte und bei allen drei ist das Symbol für Gruppenlead und im Kampf angezeigt. Habe das mal mit einem neu erstellten Char getestet, da kommt das auch sofort. 

Anbei ein Beispiel vom Mönch.

Gruß Ralf
![leiste](https://user-images.githubusercontent.com/23294004/43159829-c16e9db2-8f83-11e8-9588-3241917ed489.jpg)

**Comment by liquidbase** [comment]
Schaue ich mir morgen an.

**Comment by Potsrabe** [comment]
Hallo,
Zum Effekt bei Hexenmeister .. habe ich jetzt auch einen Fehler (Hatte noch einen HM auf dem Beta Server, wo ich jetzt nur die UI installiert habe):

1.) 2x ...faceDuffedUI\libs\plugins\oUF_SoulShards.lua:22: attempt to index field '?' (a nil value)
...faceDuffedUI\libs\plugins\oUF_SoulShards.lua:22: in function <...faceDuffedUI\libs\plugins\oUF_SoulShards.lua:9>
(tail call): ?
DuffedUI\libs\oUF\ouf.lua:211: in function `func'
DuffedUI\libs\oUF\events.lua:50: in function <DuffedUI\libs\oUF\events.lua:48>
(tail call): ?
2.) 2x ...eDuffedUI\modules\plugins\spellcooldowns.lua:941: bad argument #1 to '?' (table expected, got nil)
[C]: in function `?'
...eDuffedUI\modules\plugins\spellcooldowns.lua:941: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

Beim Druiden kommen keine Fehler.

Beim Pala ist das:
1.) 1x ...rfaceDuffedUI\libs\plugins\oUF_AuraWatch.lua:256: oUF_AuraWatch error: no spell with 114163 spell ID exists
[C]: ?
[C]: ?
FrameXML\RestrictedFrames.lua:641: in function <FrameXML\RestrictedFrames.lua:640>
FrameXML\RestrictedFrames.lua:779: in function `CallMethod'
[string "		local header = self:GetParent()..."]:51: in function <[string "		local header = self:GetParent()..."]:1>
(tail call): ?
[C]: ?
FrameXML\RestrictedExecution.lua:484: in function <FrameXML\RestrictedExecution.lua:447>
FrameXML\SecureGroupHeaders.lua:116: in function <FrameXML\SecureGroupHeaders.lua:110>
FrameXML\SecureGroupHeaders.lua:166: in function <FrameXML\SecureGroupHeaders.lua:123>
FrameXML\SecureGroupHeaders.lua:399: in function <FrameXML\SecureGroupHeaders.lua:387>
[C]: in function `Show'
FrameXML\SecureStateDriver.lua:100: in function <FrameXML\SecureStateDriver.lua:95>
FrameXML\SecureStateDriver.lua:164: in function <FrameXML\SecureStateDriver.lua:146>
[C]: in function `SetAttribute'
FrameXML\SecureStateDriver.lua:11: in function `RegisterAttributeDriver'
DuffedUI\libs\oUF\ouf.lua:652: in function `SpawnHeader'
...eDuffedUI\modules\unitframes\constructor.lua:254: in function `SpawnUF'
...eDuffedUI\modules\unitframes\constructor.lua:360: in function `LoadUF'
...eDuffedUI\modules\unitframes\constructor.lua:371: in function `?'
...eDuffedUI\modules\unitframes\constructor.lua:369: in function <...eDuffedUI\modules\unitframes\constructor.lua:369>

2.) 1x ...ceDuffedUI\libs\plugins\oUF_HolyPowerBar.lua:28: attempt to index field '?' (a nil value)
...ceDuffedUI\libs\plugins\oUF_HolyPowerBar.lua:28: in function <...ceDuffedUI\libs\plugins\oUF_HolyPowerBar.lua:9>
(tail call): ?
DuffedUI\libs\oUF\ouf.lua:211: in function `func'
DuffedUI\libs\oUF\events.lua:50: in function <DuffedUI\libs\oUF\events.lua:48>
(tail call): ?

Locals:
self = oUF_Player {
 0 = <userdata>
 UNIT_PORTRAIT_UPDATE = <function> defined @DuffedUI\libs\oUF\elements\portrait.lua:87
 __tags = <table> {
 }
 PLAYER_ENTERING_WORLD = <table> {
 }
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:314
 UNIT_SPELLCAST_INTERRUPTIBLE = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:221
 UNIT_MODEL_CHANGED = <function> defined @DuffedUI\libs\oUF\elements\portrait.lua:87
 UNIT_POWER_UPDATE = <function> defined @DuffedUI\libs\plugins\oUF_HolyPowerBar.lua:39
 UNIT_HEALTH_FREQUENT = <function> defined @DuffedUI\libs\oUF\elements\health.lua:166
 UNIT_MAXHEALTH = <function> defined @DuffedUI\libs\oUF\elements\health.lua:166
 __elements = <table> {
 }
 UNIT_POWER_FREQUENT = <function> defined @DuffedUI\libs\oUF\elements\power.lua:236
 percHP = <unnamed> {
 }
 UNIT_COMBAT = <function> defined @DuffedUI\libs\plugins\oUF_CombatFeedback.lua:62
 RAID_TARGET_UPDATE = <function> defined @DuffedUI\libs\oUF\elements\raidtargetindicator.lua:62
 Castbar = oUF_PlayerCastBar {
 }
 HolyPower = HolyPowerBar {
 }
 UNIT_SPELLCAST_NOT_INTERRUPTIBLE = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:243
 PLAYER_REGEN_DISABLED = <function> defined @DuffedUI\libs\oUF\elements\combatindicator.lua:58
 UNIT_THREAT_SITUATION_UPDATE = <function> defined @DuffedUI\core\func_UF.lua:463
 UNIT_MAXPOWER = <function> defined @DuffedUI\libs\oUF\elements\power.lua:236
 UNIT_DISPLAYPOWER = <function> defined @DuffedUI\libs\oUF\elements\power.lua:236
 style = "DuffedUI"
 PvPIndicator = <unnamed> {
 }
 UNIT_POWER_BAR_HIDE = <function> defined @DuffedUI\libs\oUF\elements\power.lua:236
 UNIT_POWER_BAR_SHOW = <function> defined @DuffedUI\libs\oUF\elements\power.lua:236
 UNIT_EXITED_VEHICLE = <function> defined @DuffedUI\libs\oUF\ouf.lua:46
 PLAYER_REGEN_ENABLED = <function> defined @DuffedUI\libs\oUF\elements\combatindicator.lua:58
 UNIT_CONNECTION = <table> {
 }
 PORTRAITS_UPDATED = <function> defined @DuffedUI\libs\oUF\elements\portrait.lua:87
 Portrait = <unnamed> {
 }
 SmoothBar = <function> defined @DuffedUI\libs\plugins\oUF_Smooth.lua:18
 HONOR_LEVEL_UPDATE = <function> defined @DuffedUI\libs\oUF\elements\pvpindicator.lua:108
 MasterLooterIndicator = <unnamed> {
 }
 RaidTargetIndicator = <unnamed> {
 }
 unit = "player"
 GROUP_ROSTER_UPDATE = <table> {
 }
 UNIT_FACTION = <table> {
 }
 PowerBorder = <unnamed> {
 }
 PARTY_LEADER_CHANGED = <table> {
 }
 UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:408
 UNIT_SPELLCAST_STOP = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:292
 PLAYER_TARGET_CHANGED = <function> defined @DuffedUI\core\func_UF.lua:463
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:378
 panel = <unnamed> {
 }
 UNIT_SPELLCAST_DELAYED = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:265
 UNIT_THREAT_LIST_UPDATE = <function> defined @DuffedUI\core\func_UF.lua:463
 Power = <unnamed> {
 }
 LeaderIndicator = <unnamed> {
 }
 UNIT_EXITING_VEHICLE = <function> defined @DuffedUI\libs\oUF\ouf.lua:46
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:193
 UNIT_SPELLCAST_START = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:107
 FlashInfo = DuffedUIFlashInfo {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @DuffedUI\libs\oUF\ouf.lua:46
 colors = <table> {
 }
 Health = <unnamed> {
 }
 HealthBorder = <unnamed> {
 }
 CombatIndicator = <unnamed> {
 }
 CombatFeedbackText = <unnamed>

Und beim Mönch :

1.) 1x ...faceDuffedUI\libs\plugins\oUF_HarmonyBar.lua:67: attempt to index field '?' (a nil value)
...faceDuffedUI\libs\plugins\oUF_HarmonyBar.lua:67: in function `func'
DuffedUI\libs\oUF\ouf.lua:211: in function `func'
DuffedUI\libs\oUF\events.lua:50: in function <DuffedUI\libs\oUF\events.lua:48>
(tail call): ?

Locals:
self = oUF_Player {
 0 = <userdata>
 UNIT_PORTRAIT_UPDATE = <function> defined @DuffedUI\libs\oUF\elements\portrait.lua:87
 __tags = <table> {
 }
 PLAYER_ENTERING_WORLD = <table> {
 }
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:314
 UNIT_SPELLCAST_INTERRUPTIBLE = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:221
 UNIT_FACTION = <table> {
 }
 UNIT_POWER_UPDATE = <function> defined @DuffedUI\libs\plugins\oUF_HarmonyBar.lua:78
 UNIT_HEALTH_FREQUENT = <function> defined @DuffedUI\libs\oUF\elements\health.lua:166
 UNIT_MAXHEALTH = <function> defined @DuffedUI\libs\oUF\elements\health.lua:166
 __elements = <table> {
 }
 UNIT_POWER_FREQUENT = <function> defined @DuffedUI\libs\oUF\elements\power.lua:236
 percHP = <unnamed> {
 }
 UNIT_COMBAT = <function> defined @DuffedUI\libs\plugins\oUF_CombatFeedback.lua:62
 RAID_TARGET_UPDATE = <function> defined @DuffedUI\libs\oUF\elements\raidtargetindicator.lua:62
 Castbar = oUF_PlayerCastBar {
 }
 UNIT_DISPLAYPOWER = <table> {
 }
 UNIT_SPELLCAST_NOT_INTERRUPTIBLE = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:243
 PLAYER_REGEN_DISABLED = <function> defined @DuffedUI\libs\oUF\elements\combatindicator.lua:58
 UNIT_THREAT_SITUATION_UPDATE = <function> defined @DuffedUI\core\func_UF.lua:463
 UNIT_POWER_BAR_HIDE = <function> defined @DuffedUI\libs\oUF\elements\power.lua:236
 UNIT_POWER_BAR_SHOW = <function> defined @DuffedUI\libs\oUF\elements\power.lua:236
 style = "DuffedUI"
 PvPIndicator = <unnamed> {
 }
 PLAYER_REGEN_ENABLED = <function> defined @DuffedUI\libs\oUF\elements\combatindicator.lua:58
 PORTRAITS_UPDATED = <function> defined @DuffedUI\libs\oUF\elements\portrait.lua:87
 UNIT_EXITED_VEHICLE = <function> defined @DuffedUI\libs\oUF\ouf.lua:46
 UNIT_MODEL_CHANGED = <function> defined @DuffedUI\libs\oUF\elements\portrait.lua:87
 UNIT_CONNECTION = <table> {
 }
 HONOR_LEVEL_UPDATE = <function> defined @DuffedUI\libs\oUF\elements\pvpindicator.lua:108
 Portrait = <unnamed> {
 }
 SmoothBar = <function> defined @DuffedUI\libs\plugins\oUF_Smooth.lua:18
 UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:408
 MasterLooterIndicator = <unnamed> {
 }
 RaidTargetIndicator = <unnamed> {
 }
 unit = "player"
 GROUP_ROSTER_UPDATE = <table> {
 }
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:378
 PowerBorder = <unnamed> {
 }
 PARTY_LEADER_CHANGED = <table> {
 }
 UNIT_SPELLCAST_DELAYED = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:265
 UNIT_SPELLCAST_STOP = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:292
 PLAYER_TARGET_CHANGED = <function> defined @DuffedUI\core\func_UF.lua:463
 UNIT_MAXPOWER = <table> {
 }
 panel = <unnamed> {
 }
 Power = <unnamed> {
 }
 UNIT_THREAT_LIST_UPDATE = <function> defined @DuffedUI\core\func_UF.lua:463
 UNIT_SPELLCAST_START = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:107
 LeaderIndicator = <unnamed> {
 }
 UNIT_EXITING_VEHICLE = <function> defined @DuffedUI\libs\oUF\ouf.lua:46
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:193
 HarmonyBar = HarmonyBar {
 }
 FlashInfo = DuffedUIFlashInfo {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @DuffedUI\libs\oUF\ouf.lua:46
 colors = <table> {
 }
 Health = <unnamed> {
 }
 HealthBorder = <unnamed> {
 }
 CombatIndicator = <unnamed> {
 }
 CombatFeedbackText = <unnamed> {
 }
 UNIT_SPELLCAST_FAILED = <function> defined @DuffedUI\libs\oUF\elements\castbar.lua:165
}
event = "PLAYER_ENTE

Und da kommt noch ein Fehler mit Orderhall:

1x DuffedUI\modules\skins\orderhall.lua:19: attempt to index global 'OrderHallMissionFrame' (a nil value)
DuffedUI\modules\skins\orderhall.lua:19: in function `skinfunc'
DuffedUI\core\func_Skins.lua:17: in function <DuffedUI\core\func_Skins.lua:8>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:639: in function `OrderHall_LoadUI'
FrameXML\UIParent.lua:718: in function `OrderHall_CheckCommandBar'
FrameXML\UIParent.lua:2043: in function <FrameXML\UIParent.lua:1089>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "RIGHT"
(*temporary) = OrderHallCommandBar {
 0 = <userdata>
 insettop = <unnamed> {
 }
 WorldMapButton = <unnamed> {
 }
 RequestCategoryInfo = <function> defined @Blizzard_OrderHallUI\Blizzard_OrderHallCommandBar.lua:93
 Currency = <unnamed> {
 }
 insetbottom = <unnamed> {
 }
 isInsetDone = true
 insetinsideright = <unnamed> {
 }
 Background = <unnamed> {
 }
 insetright = <unnamed> {
 }
 insetinsidebottom = <unnamed> {
 }
 RefreshCurrency = <function> defined @Blizzard_OrderHallUI\Blizzard_OrderHallCommandBar.lua:131
 OnShow = <function> defined @Blizzard_OrderHallUI\Blizzard_OrderHallCommandBar.lua:30
 CurrencyHitTest = <unnamed> {
 }
 OnLoad = <function> defined @Blizzard_OrderHallUI\Blizzard_OrderHallCommandBar.lua:7
 OnHide = <function> defined @Blizzard_OrderHallUI\Blizzard_OrderHallCommandBar.lua:52
 insetinsideleft = <unnamed> {
 }
 insetleft = <unnamed> {
 }
 OnEvent = <function> defined @Blizzard_OrderHallUI\Blizzard_OrderHallCommandBar.lua:69
 currency = 1220
 RefreshCategories = <function> defined @Blizzard_OrderHallUI\Blizzard_OrderHallCommandBar.lua:102
 AreaName = <unnamed> {
 }
 CurrencyIcon = <unnamed> {
 }
 categoryPool = <table> {
 }
 RefreshAll = <function> defined @Blizzard_OrderHallUI\Blizzard_OrderHallCommandBar.lua:97
 insetinsidetop = <unnamed> {
 }
 ClassIcon = <unnamed> {
 }
}
(*temporary) = -5
(*temporary) = -2
(*temporary) = <userdata>
(*temporary) = <userdata>
(*temporary) = 0.125
(*temporary) = <userdata>
(*temporary) = <userdata>
(*temporary) = 1.0015649452269
(*temporary) = 1
(*temporary) = 1.4984375
(*temporary) = 1
(*temporary) = "attempt to index global 'OrderHallMissionFrame' (a nil value)"
D = <table> {
 countOffsets = <table> {
 }
 SetFontString = <function> defined @DuffedUI\core\func_Core.lua:87
 Scale = <function> defined @DuffedUI\core\api.lua:19
 PostUpdateAura = <function> defined @DuffedUI\core\func_UF.lua:312
 Currency = <function> defined @DuffedUI\core\func_Core.lua:48
 DataTextPosition = <function> defined @DuffedUI\core\func_Core.lua:97
 UpdateTargetDebuffsHeader = <function> defined @DuffedUI\core\func_UF.lua:341
 MyRealm = "Anduin"
 CoAutor = <table> {
 }
 move = <unnamed> {
 }
 IconCoord = <table> {
 }
 Toc = 80000
 MicroMenu = <table> {
 }
 SidebarButtonsize = 23.035993740219
 Spells = <table> {
 }
 LoadUF = <function> defined @DuffedUI\modules\unitframes\constructor.lua:357
 SpawnUF = <function> defined @DuffedUI\modules\unitframes\constructor.lua:46
 ShiftBarUpdate = <function> defined @DuffedUI\core\func_Core.lua:168
 PetBarUpdate = <function> defined @DuffedUI\core\func_Core.lua:200
 CreateBtn = <function> defined @DuffedUI\core\func_Core.lua:347
 SetDefaultActionButtonCooldownFont = "Addons\DuffedUI\medias\fonts\normal_font.ttf"
 ConstructUF = <function> defined @DuffedUI\modules\unitframes\constructor.lua:17
 UpdateManaLevel = <function> defined @DuffedUI\core\func_UF.lua:442
 ConstructUFMaintank = <function> defined @DuffedUI\modules\unitframes\units\maintank.lua:17
 Class = "MONK"
 ScreenHeight = 1080
 petbuttonspacing = 4.0062597809077
 Dummy = <function> defined @DuffedUI\core\constants.lua:7
 ConstructUFArena = <function> defined @DuffedUI\modules\unitframes\units\arena.lua:25
 ConstructUFFocusTarget = <function> defined @DuffedUI\modules\unitframes\units\focustarget.lua:17
 ConstructUFBoss = <function> defined @DuffedUI\modules\unitframes\units\boss.lua:25
 StyleActionBarFlyout = <function> defined @DuffedUI\modules\actionbars\style.lua:207
 ColorTemplate = <table> {
 }
 ChatSetup = <function> defined @DuffedUI\core\install.l


P.S.:  Und ich muss noch eine dumme Frage stellen. Ich habe auf der Rechten Seite einen roten Pfeil, wenn man am Rand mit der Maus lang geht. Da klappt aber nichts auf (Standard Installation ohne Anpassungen).

Gruß Ralf

**Comment by liquidbase** [comment]
Schau mal ob die Rechte Actionbar bei dir deaktiviert ist. Die wird
normalerweise dort verankert. Macht derzeit auch Probleme.

**Comment by liquidbase** [comment]
Ressourcen für die Klassen sind jetzt gefixt.

**Comment by Potsrabe** [comment]
Hallo,
Super, werde ich heute Abend dann testen. Hattest Du das darüber mit time.lua und co. auch gelesen?

Danke!

Gruß Ralf

**Comment by liquidbase** [comment]
Jips der Fix ist bereits drin. Habe ich heute Vormittag implementiert.

**Comment by Potsrabe** [comment]
Hallo,
So erst einmal Danke, das mit den Ressourcen passt jetzt. Der Spellcooldown Fehler bei meinen Test Hexer kommt, weil die Spells der Volksfähigkeit für die Dunkeleisenzwerge fehlen:

		['DarkIronDwarf'] = {
			265221, -- Fireblood
			265225, -- Mole Machine
		},

Dann habe ich allerdings noch ein Problem gesehen (weiß nicht, ob das gestern auch schon war). Die Begleiterleiste ist zwar da (Jäger, Magier, Hexer) , aber es sind keine Spell Symbole zu sehen sondern nur schwarze und Grüne Flächen Die an einigen Stellen aufleuchten . Es komme aber keine Fehlermeldung. Mehrfach Reload gemacht und Install. 

Gruß Ralf

Hier Beispiel Hexer:

![begleiter_leiste](https://user-images.githubusercontent.com/23294004/43216569-a1fbcd26-903f-11e8-943b-39b312f3882c.png)

**Comment by liquidbase** [comment]
Der Fehler war schon immer da, konnte ich bisher noch nie richtig fixen. Steht aber mit auf der Agenda und die Volksfertigkeiten vom Dunkeleisenzwerg füge ich gerade noch hinzu.

**Comment by liquidbase** [comment]
PetActionBar fixed
