### ISSUE TITLE
LUA Fehler bei leerer Exp Bar

### ISSUE THREAD

**Issue by fiffzek** [liquidbase/DuffedUIv8#80]
Wenn man MaxLevel ist und ein Ruf bei einer Fraktion trackt mit der man schon ehrfürchtig ist kommt 
bei MouseOver dann diese Fehlermeldung. Die Exp/Rep Bar ist dann zu sehen, aber leer.
Es gibt ja seit Legion die Möglichkeit über ehrfürchtig hinaus Ruf zu bekommen. Außerdem ist dann der Tooltip nicht richtig geskinnt.
Siehe Bild [https://imgur.com/a/ngCflJT](https://imgur.com/a/ngCflJT)
 
```
5x integer overflow attempting to store -nan(ind)
[C]: in function `format'
DuffedUI\modules\misc\experience.lua:127: in function <DuffedUI\modules\misc\experience.lua:113>

Locals:
(*temporary) = "Rep: %s/%s (%d%%)"
(*temporary) = "0"
(*temporary) = "0"
(*temporary) = -nan(ind)

```

**Comment by liquidbase** [comment]
Bin ich derzeit dran und sollte heute Abend noch was zu kommen

**Comment by liquidbase** [comment]
Fehler ist gefixt
