### ISSUE TITLE
Fehler bei Öffnen des Characterfensters

### ISSUE THREAD

**Issue by fiffzek** [liquidbase/DuffedUIv8#81]
Beim Öffnen des Char-Fensters kommt dieser Fehler
```
10x FrameXML\CharacterFrame.lua:184: attempt to perform arithmetic on a nil value
FrameXML\CharacterFrame.lua:184: in function `CharacterFrame_TabBoundsCheck'
[string "*:OnShow"]:2: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
FrameXML\UIParent.lua:3131: in function `ShowUIPanel'
FrameXML\CharacterFrame.lua:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER2"]:1: in function <[string "TOGGLECHARACTER2"]:1>

Locals:
self = CharacterFrameTab1 {
 0 = <userdata>
 isSkinned = true
 Backdrop = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = CharacterFrame {
 0 = <userdata>
 TitleText = CharacterFrameTitleText {
 }
 portrait = CharacterFramePortrait {
 }
 LeftBorder = CharacterFrameLeftBorder {
 }
 ignoreFramePositionManager = true
 isInsetDone = true
 insetinsideright = <unnamed> {
 }
 insetinsideleft = <unnamed> {
 }
 insetinsidebottom = <unnamed> {
 }
 insetbottom = <unnamed> {
 }
 insetinsidetop = <unnamed> {
 }
 TopRightCorner = CharacterFrameTopRightCorner {
 }
 TopLeftCorner = CharacterFrameTopLeftCorner {
 }
 Bg = CharacterFrameBg {
 }
 CloseButton = CharacterFrameCloseButton {
 }
 RightBorder = CharacterFrameRightBorder {
 }
 TopBorder = CharacterFrameTopBorder {
 }
 ReputationTabHelpBox = <unnamed> {
 }
 TopTileStreaks = CharacterFrameTopTileStreaks {
 }
 TitleBg = CharacterFrameTitleBg {
 }
 BottomBorder = CharacterFrameBottomBorder {
 }
 insettop = <unnamed> {
 }
 OnLoad = <function> defined @SharedXML\SharedUIPanelTemplates.lua:860
 numTabs = 3
 BotRightCorner = CharacterFrameBotRightCorner {
 }
 Inset = CharacterFrameInset {
 }
 insetright = <unnamed> {
 }
 BotLeftCorner = CharacterFrameBotLeftCorner {
 }
 PortraitFrame = CharacterFramePortraitFrame {
 }
 selectedTab = 2
 insetleft = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = <function> defined @SharedXML\SharedUIPanelTemplates.lua:446
(*temporary) = CharacterFrameTab3 {
 0 = <userdata>
 isSkinned = true
 Backdrop = <unnamed> {
 }
}
(*temporary) = 0
(*temporary) = nil
(*temporary) = 36
(*temporary) = 88
(*temporary) = "attempt to perform arithmetic on a nil value"
NUM_CHARACTERFRAME_TABS = 3
CharTabtable = <table> {
}
CompareFrameSize = <function> defined @FrameXML\CharacterFrame.lua:170

```

**Comment by liquidbase** [comment]
Das muss ich mir mal genauer anschauen. Hatte gestern den Fehler nicht gehabt als ich nochmal alle Skins durchgegangen bin. Hast du den Fehler auf allen Chars oder nur auf einem bestimmten?

**Comment by fiffzek** [comment]
Habe ich auf allen Charakteren

**Comment by Potsrabe** [comment]
Hallo,
Kann es sein, das da gestern ein Update gekommen ist? Ich hatte die aktuelle Version gestern auch getestet und die war eigentlich Fehlerfrei.

Gruß Ralf

**Comment by Potsrabe** [comment]
Hallo,
Ich habe das eben noch mal getestet mit der aktuellen Version vom Github. Bei mir tritt der Fehler nicht auf. 

Gruß Ralf

**Comment by fiffzek** [comment]
Ich habe es vorhin auch noch mal probiert und nur die Duffed Addons aktiviert. Bekomme den Fehler.

**Comment by Potsrabe** [comment]
Hallo,
Nachdem ich jetzt einiges mit einem anderen Addon getestet habe. Nach mehreren Reloads kam der Fehler jetzt:

2x FrameXML\CharacterFrame.lua:184: attempt to perform arithmetic on a nil value
FrameXML\CharacterFrame.lua:184: in function `CharacterFrame_TabBoundsCheck'
[string "*:OnShow"]:2: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
FrameXML\UIParent.lua:3131: in function `ShowUIPanel'
FrameXML\CharacterFrame.lua:21: in function `ToggleCharacter'
...faceDuffedUI\modules\datatext\durability-Haltbarkeit.lua:44: in function <...faceDuffedUI\modules\datatext\durability.lua:44>

**Comment by Potsrabe** [comment]
Hier noch die Locals dazu:

Locals:
self = CharacterFrameTab1 {
 0 = <userdata>
 isSkinned = true
 Backdrop = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = CharacterFrame {
 0 = <userdata>
 TitleText = CharacterFrameTitleText {
 }
 portrait = CharacterFramePortrait {
 }
 LeftBorder = CharacterFrameLeftBorder {
 }
 ignoreFramePositionManager = true
 isInsetDone = true
 insetinsideright = <unnamed> {
 }
 insetinsideleft = <unnamed> {
 }
 insetinsidebottom = <unnamed> {
 }
 insetbottom = <unnamed> {
 }
 insetinsidetop = <unnamed> {
 }
 TopRightCorner = CharacterFrameTopRightCorner {
 }
 TopLeftCorner = CharacterFrameTopLeftCorner {
 }
 Bg = CharacterFrameBg {
 }
 CloseButton = CharacterFrameCloseButton {
 }
 RightBorder = CharacterFrameRightBorder {
 }
 TopBorder = CharacterFrameTopBorder {
 }
 ReputationTabHelpBox = <unnamed> {
 }
 TopTileStreaks = CharacterFrameTopTileStreaks {
 }
 TitleBg = CharacterFrameTitleBg {
 }
 BottomBorder = CharacterFrameBottomBorder {
 }
 insettop = <unnamed> {
 }
 OnLoad = <function> defined @SharedXML\SharedUIPanelTemplates.lua:860
 numTabs = 3
 BotRightCorner = CharacterFrameBotRightCorner {
 }
 Inset = CharacterFrameInset {
 }
 insetright = <unnamed> {
 }
 BotLeftCorner = CharacterFrameBotLeftCorner {
 }
 PortraitFrame = CharacterFramePortraitFrame {
 }
 selectedTab = 1
 insetleft = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = <function> defined @SharedXML\SharedUIPanelTemplates.lua:446
(*temporary) = CharacterFrameTab3 {
 0 = <userdata>
 isSkinned = true
 Backdrop = <unnamed> {
 }
}
(*temporary) = 0
(*temporary) = nil
(*temporary) = 36
(*temporary) = 88
(*temporary) = "attempt to perform arithmetic on a nil value"
NUM_CHARACTERFRAME_TABS = 3
CharTabtable = <table> {
}
CompareFrameSize = <function> defined @FrameXML\CharacterFrame.lua:170

**Comment by liquidbase** [comment]
Fehler ist gefixt

**Comment by liquidbase** [comment]
Fixed with the next push
