### ISSUE TITLE
LUA Fehler beim Betreten einer Instanz

### ISSUE THREAD

**Issue by fiffzek** [liquidbase/DuffedUIv8#82]
Beim Betreten einer Ini kommt dieser Fehler.
An der Minimap werden dann keine Koordinaten angezeigt; nur x, x

```
8x Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken)
[C]: in function `GetPlayerMapPosition'
DuffedUI\modules\maps\minimap.lua:137: in function <DuffedUI\modules\maps\minimap.lua:131>

Locals:
(*temporary) = "Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken)"

```

**Comment by liquidbase** [comment]
Normale 5er-Instanz oder Raid?

**Comment by fiffzek** [comment]
5er Ini

**Comment by liquidbase** [comment]
Dann ist jetzt nur noch die Frage welcher Content. Bin gerade die aktuellen aus Legion abgeflogen und da gab es keinen Fehler. Weder Minimap noch Worldmap.

**Comment by fiffzek** [comment]
Ich war in Neltharions Lair Mythisch

**Comment by liquidbase** [comment]
Okay dann schau ich mir die Mythics mal an, kann sein das es da eventuell ein Problem gibt

**Comment by fiffzek** [comment]
Update: Gerade mal Random Battleground Alterac Tal gejoined. Da kommt auch der Fehler

**Comment by liquidbase** [comment]
Fixed
