### ISSUE TITLE
Not that I don't like germans.....

### ISSUE THREAD

**Issue by Stroider** [liquidbase/DuffedUIv8#84]
Hey guys,

been using Duffed since god knows and will probably quit the game when Duffed do ^^

But one thing, my schooldeutch is more then lacking (if I'm not pissed drunk and has been transformed into a member of the TV serie The Clinic) so when I'm sober I have a hard time understanding the german language.

Therefor I would really appriciate if you guys could at least do a small info text about the issues so I have a chance to be on par.

Vielen dank,

Danz

**Comment by liquidbase** [comment]
Nope it's okay :)
