### ISSUE TITLE
Blizzard chat buttons appearing when scolling in chat

### ISSUE THREAD

**Issue by Skunkzord** [liquidbase/DuffedUIv8#85]
Hey Liquidbase,

I have found a small issue in the chat frames.
Happens on both left and right side of the screen.
https://imgur.com/a/EQJVOqY

**Comment by liquidbase** [comment]
Jips I have noticed the same. Funfact .. the code to kill these buttons is already present...

**Comment by liquidbase** [comment]
Fixed 
8.78 will go online later today.
