### ISSUE TITLE
Problems with Trainer Skin

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8#87]
Hello,
It gives a Problem with Trainer Skin. With Trainer Skin enabled it is not possible to learn something (learn button will not be enabled). After Deactive the Skinning in Project Azilroka, it works without Problems.

BR Ralf

**Comment by Potsrabe** [comment]
Hello,
That error will be in both Versions , Github and wowinterface.com

BR ralf

**Comment by liquidbase** [comment]
I'll check this when I'm back at home.

**Comment by Rav99** [comment]
Hiho. I have try to fix the problem with the trainer learn button. Look at pr :)

**Comment by Potsrabe** [comment]
Hello Rav, nice work! 

Works fine with the changes.

BR Ralf

**Comment by Rav99** [comment]
Nice. Can you check the scrollthingy too pls? :)

**Comment by Potsrabe** [comment]
Hello Rav,
It will be all o.k.. Filter works, scroll works.

BR Ralf

**Comment by liquidbase** [comment]
Fixed
8.78 will go online later today.
