### ISSUE TITLE
New error massages and no Shape Shift Bar for Druids

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8#89]
1.) 1x DuffedUI\modules\actionbars\barpet.lua:47: attempt to call field 'StylePet' (a nil value)
DuffedUI\modules\actionbars\barpet.lua:47: in function <DuffedUI\modules\actionbars\barpet.lua:16>

2.) 3x FrameXML\CharacterFrame.lua:184: attempt to perform arithmetic on a nil value
FrameXML\CharacterFrame.lua:184: in function `CharacterFrame_TabBoundsCheck'
[string "*:OnShow"]:2: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
FrameXML\UIParent.lua:3131: in function `ShowUIPanel'
FrameXML\CharacterFrame.lua:21: in function `ToggleCharacter'
...rfaceAddOnSkins\Skins\Blizzard\Character-Charakter.lua:9: in function <...rfaceAddOnSkins\Skins\Blizzard\Character.lua:7>
[C]: ?
AddOnSkins\Core\Core.lua:173: in function `CallSkin'
AddOnSkins\Core\Core.lua:230: in function `?'
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...jectAzilroka\Libs\Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...jectAzilroka\Libs\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

3.) 6x DuffedUI\modules\actionbars\barshift.lua:77: '<name>' expected near '['

4.) 6x DuffedUI\modules\actionbars\style.lua:8: '(' expected near '['

5.) 10x DuffedUI\modules\actionbars\barpet.lua:59: attempt to call field 'StylePet' (a nil value)
DuffedUI\modules\actionbars\barpet.lua:59: in function <DuffedUI\modules\actionbars\barpet.lua:16>

BR Ralf

**Comment by liquidbase** [comment]
Which version? Actual 8.77 from wowinterface / curse or from GitHub? If the version is from GitHub please use the version from wowinterface / curse. Currently the GitHub version has a code review and something could not work correctly.

**Comment by Potsrabe** [comment]
Actual 8.77 from GitHub.
Ahh O.K. !

BR Ralf

**Comment by Potsrabe** [comment]
Hello,
With Version of wowinterface no Errors. 

BR Ralf
