### ISSUE TITLE
Square Minimap Buttons/Bar not working

### ISSUE THREAD

**Issue by Rushgarroth** [liquidbase/DuffedUIv8#94]
The checkbox is checked and therefore it should be enabled. But there arent options like the old Square minimap buttons addon i was still using. I disabled the old one and got your new ProjectAzilroka compilation because it was continued there. But for me it isnt working. Am i missing something or are there no options for it? Because even when enabled the minimap buttons arent in a big square box and just floating around the map as if there wasnt anything enabled

**Comment by Rushgarroth** [comment]
I only get to the Point in Menue when i open ElvUi and go ti ProjektAzilroka => https://imgur.com/a/PQvRy9j
And as you can see, it is checked but the minimap doesnt look like there is anything enabled

**Comment by liquidbase** [comment]
That is a issue of ElvUI not of DuffedUI. Please make bugreport on the tukui-forum. DuffedUI and ElvUI are not the same interface.

**Comment by Rushgarroth** [comment]
Oh i thought you could use it withou duffed. Since you could before. Would be a shame if i had to abandon that addon.

The old Square minimap buttons addon works fine so far except for one error.

"1740x Couldn't open SquareMinimapButtons\
!BugGrabber\BugGrabber.lua:578: in function <!BugGrabber\BugGrabber.lua:578>"

Else everything is working, all settings and so on

**Comment by liquidbase** [comment]
Nope I used it with DuffedUI in combination. Azilroka has merged all his separat projects into one, maned ProjectAzilroka. All standalone addons from expect AddOnSkins are now obsolet. You have to use ProjectAzilroka.

**Comment by Rushgarroth** [comment]
Damn, guess i have to live with the errormessage wich is spamming me or with an unclean minimap then, since there is only one addon wich does sort them similar in a Minimap box, but doesnt look as sleek.
Alright thanks for your time

**Comment by liquidbase** [comment]
You're welcome :)
