### ISSUE TITLE
Some liitle Problems

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8#99]
Hello, Since new patch it give some Little Problems. I think they are all results from AddOn Skins Modul. 
First I get Info, That Alizroka AddOn Skins are outdated. Second I have the Feeling, That Loot window are not skinned. Third If I will be in Bank, the Bank Window have two Windows, one Skinned and one not skinned.

BR Ralf aka Rolfman

**Comment by Rav99** [comment]
Hiho see my pr, maybe it works :) @Potsrabe

**Comment by Potsrabe** [comment]
Hello Rav,
Thank You for Information. But I have a last Problem, That I have forget yesterday. If I look on my Life I can se it will be full, but the Untitframe Shows me 99 % und yesterday I have seen also 120 % .

BR Ralf

**Comment by Potsrabe** [comment]
Sorry ,

Wrong Button :-)

BR Ralf

**Comment by Rav99** [comment]
I have try to fix this too.
i have seen this error too, after the changes it shows correct % for me but @liquidbase take a look

**Comment by Potsrabe** [comment]
O.K.,
Than I will wait for corrections from Your pull Request.

Thank You !

BR Ralf

**Comment by Potsrabe** [comment]
Hello Rav99,
I have made the changes manually and it works for me also fine!

Thank You !!!

BR ralf

**Comment by Rav99** [comment]
Thx for report and have nice loot :)

**Comment by Potsrabe** [comment]
O.K. , my brother told me, (and I have test it) in Character Window the Tab Currency is missing.
And if I have in Alizroka AddOn Skins "Azerit" activated it gives an error message and it will be deactivated automaticly.

BR Ralf

**Comment by Rav99** [comment]
i have fixed the currency button, but i cant rep the azerit thingy. i have all addonskins on, no error. can you paste the error pls? @Potsrabe

**Comment by Potsrabe** [comment]
Hello,
Here are the error Text:
```lua
Interface\AddOns\AddOnSkins\Skins\Blizzard\BfA.lua:10: attempt to index field 'Shadow' (a nil value)
```

Generated with AddOnSkins 4.04

BR

Ralf

**Comment by Rav99** [comment]
I have committed this line out ... hope it works :) @Potsrabe

**Comment by Potsrabe** [comment]
Hello Rav,
All Changes works for me without Errors.

BR Ralf
